version: '3.4'

networks:
  shimei-network-api:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16

services:
  japanesepersongeneratorapi:
    image: ${DOCKER_REGISTRY-}japanesepersongeneratorapi
    container_name: shimei-api
    ports:
        - "448:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_Kestrel__Certificates__Default__Password=$CERT_PASS
      - ASPNETCORE_Kestrel__Certificates__Default__Path=$CERT_PATH
    volumes:
      - ~/.aspnet/https:/https:ro
    build:
      context: .
      dockerfile: JapanesePersonGeneratorApi/Dockerfile
    restart: always
    networks:
        shimei-network-api:
            ipv4_address: 172.30.0.3

  japanesepersongeneratorspa:
    container_name: shimei-spa
    ports:
        - "2092:80"
    build:
      context: .
      dockerfile: japanesepersongenerator.spa/Dockerfile
    restart: always
    networks:
        shimei-network-api:
            ipv4_address: 172.30.0.8

  shimei-tunnel-api:
    container_name: shimei-cloudflared-tunnel-api
    image: cloudflare/cloudflared
    restart: unless-stopped
    command: tunnel run
    environment:
      - TUNNEL_TOKEN=${TUNEL_TOKEN}
    networks:
        shimei-network-api:
            ipv4_address: 172.30.0.5
